PREFIX gf: <http://www.gra.fo/schema/untitled-ekg#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT distinct ?property ?label WHERE {
    {?property rdfs:domain gf:Author}
    ?property rdfs:label ?label
}
